insert into states (state_code, state_name) values (35,	'ANDAMAN & NICOBAR ISLANDS');
insert into states (state_code, state_name) values (28,	'ANDHRA PRADESH');
insert into states (state_code, state_name) values (12,	'ARUNACHAL PRADESH');
insert into states (state_code, state_name) values (18,	'ASSAM');
insert into states (state_code, state_name) values (10,	'BIHAR');
insert into states (state_code, state_name) values (04,	'CHANDIGARH');
insert into states (state_code, state_name) values (22,	'CHHATTISGARH');
insert into states (state_code, state_name) values (26,	'DADRA & NAGAR HAVELI');
insert into states (state_code, state_name) values (25,	'DAMAN AND DIU');
insert into states (state_code, state_name) values (30,	'GOA');
insert into states (state_code, state_name) values (24,	'GUJARAT');
insert into states (state_code, state_name) values (06,	'HARYANA');
insert into states (state_code, state_name) values (02,	'HIMACHAL PRADESH');
insert into states (state_code, state_name) values (01,	'JAMMU AND KASHMIR');
insert into states (state_code, state_name) values (20,	'JHARKHAND');
insert into states (state_code, state_name) values (29,	'KARNATAKA');
insert into states (state_code, state_name) values (32,	'KERALA');
insert into states (state_code, state_name) values (31,	'LAKSHADWEEP');
insert into states (state_code, state_name) values (23,	'MADHYA PRADESH');
insert into states (state_code, state_name) values (27,	'MAHARASHTRA');
insert into states (state_code, state_name) values (14,	'MANIPUR');
insert into states (state_code, state_name) values (17,	'MEGHALAYA');
insert into states (state_code, state_name) values (15,	'MIZORAM');
insert into states (state_code, state_name) values (13,	'NAGALAND');
insert into states (state_code, state_name) values (07,	'NCT OF DELHI');
insert into states (state_code, state_name) values (21,	'ODISHA');
insert into states (state_code, state_name) values (34,	'PUDUCHERRY');
insert into states (state_code, state_name) values (03,	'PUNJAB');
insert into states (state_code, state_name) values (08,	'RAJASTHAN');
insert into states (state_code, state_name) values (11,	'SIKKIM');
insert into states (state_code, state_name) values (33,	'TAMIL NADU');
insert into states (state_code, state_name) values (36,	'TELANGANA');
insert into states (state_code, state_name) values (16,	'TRIPURA');
insert into states (state_code, state_name) values (09,	'UTTAR PRADESH');
insert into states (state_code, state_name) values (05,	'UTTARAKHAND');
insert into states (state_code, state_name) values (19,	'WEST BENGAL');


insert into districts (district_code, district_name, state_code) values (638,	'Nicobars',	35);
insert into districts (district_code, district_name, state_code) values (639,	'North and Middle Andaman',	35);
insert into districts (district_code, district_name, state_code) values (640,	'South Andaman',	35);
insert into districts (district_code, district_name, state_code) values (553,	'Anantapur',	28);
insert into districts (district_code, district_name, state_code) values (554,	'Chittoor',	28);
insert into districts (district_code, district_name, state_code) values (545,	'East Godavari',	28);
insert into districts (district_code, district_name, state_code) values (548,	'Guntur',	28);
insert into districts (district_code, district_name, state_code) values (547,	'Krishna',	28);
insert into districts (district_code, district_name, state_code) values (552,	'Kurnool',	28);
insert into districts (district_code, district_name, state_code) values (549,	'Prakasam',	28);
insert into districts (district_code, district_name, state_code) values (550,	'Sri Potti Sriramulu Nellore',	28);
insert into districts (district_code, district_name, state_code) values (542,	'Srikakulam',	28);
insert into districts (district_code, district_name, state_code) values (544,	'Visakhapatnam',	28);
insert into districts (district_code, district_name, state_code) values (543,	'Vizianagaram',	28);
insert into districts (district_code, district_name, state_code) values (546,	'West Godavari',	28);
insert into districts (district_code, district_name, state_code) values (551,	'Y.S.R.',	28);
insert into districts (district_code, district_name, state_code) values (260,	'Anjaw',	12);
insert into districts (district_code, district_name, state_code) values (253,	'Changlang',	12);
insert into districts (district_code, district_name, state_code) values (257,	'Dibang Valley',	12);
insert into districts (district_code, district_name, state_code) values (247,	'East Kameng',	12);
insert into districts (district_code, district_name, state_code) values (251,	'East Siang',	12);
insert into districts (district_code, district_name, state_code) values (953,	'Kra Daadi',	12);
insert into districts (district_code, district_name, state_code) values (256,	'Kurung Kumey',	12);
insert into districts (district_code, district_name, state_code) values (259,	'Lohit',	12);
insert into districts (district_code, district_name, state_code) values (258,	'Lower Dibang Valley',	12);
insert into districts (district_code, district_name, state_code) values (954,	'Lower Siang',	12);
insert into districts (district_code, district_name, state_code) values (255,	'Lower Subansiri',	12);
insert into districts (district_code, district_name, state_code) values (955,	'Namsai',	12);
insert into districts (district_code, district_name, state_code) values (248,	'Papum Pare',	12);
insert into districts (district_code, district_name, state_code) values (956,	'Siang',	12);
insert into districts (district_code, district_name, state_code) values (245,	'Tawang',	12);
insert into districts (district_code, district_name, state_code) values (254,	'Tirap',	12);
insert into districts (district_code, district_name, state_code) values (252,	'Upper Siang',	12);
insert into districts (district_code, district_name, state_code) values (249,	'Upper Subansiri',	12);
insert into districts (district_code, district_name, state_code) values (246,	'West Kameng',	12);
insert into districts (district_code, district_name, state_code) values (250,	'West Siang',	12);
insert into districts (district_code, district_name, state_code) values (324,	'Baksa',	18);
insert into districts (district_code, district_name, state_code) values (303,	'Barpeta',	18);
insert into districts (district_code, district_name, state_code) values (957,	'Biswanath',	18);
insert into districts (district_code, district_name, state_code) values (319,	'Bongaigaon',	18);
insert into districts (district_code, district_name, state_code) values (316,	'Cachar',	18);
insert into districts (district_code, district_name, state_code) values (958,	'Charaideo',	18);
insert into districts (district_code, district_name, state_code) values (320,	'Chirang',	18);
insert into districts (district_code, district_name, state_code) values (325,	'Darrang',	18);
insert into districts (district_code, district_name, state_code) values (308,	'Dhemaji',	18);
insert into districts (district_code, district_name, state_code) values (301,	'Dhubri',	18);
insert into districts (district_code, district_name, state_code) values (310,	'Dibrugarh',	18);
insert into districts (district_code, district_name, state_code) values (315,	'Dima Hasao',	18);
insert into districts (district_code, district_name, state_code) values (302,	'Goalpara',	18);
insert into districts (district_code, district_name, state_code) values (313,	'Golaghat',	18);
insert into districts (district_code, district_name, state_code) values (318,	'Hailakandi',	18);
insert into districts (district_code, district_name, state_code) values (959,	'Hojai',	18);
insert into districts (district_code, district_name, state_code) values (312,	'Jorhat',	18);
insert into districts (district_code, district_name, state_code) values (321,	'Kamrup',	18);
insert into districts (district_code, district_name, state_code) values (322,	'Kamrup Metropolitan',	18);
insert into districts (district_code, district_name, state_code) values (314,	'Karbi Anglong',	18);
insert into districts (district_code, district_name, state_code) values (317,	'Karimganj',	18);
insert into districts (district_code, district_name, state_code) values (300,	'Kokrajhar',	18);
insert into districts (district_code, district_name, state_code) values (307,	'Lakhimpur',	18);
insert into districts (district_code, district_name, state_code) values (960,	'Majuli',	18);
insert into districts (district_code, district_name, state_code) values (304,	'Morigaon',	18);
insert into districts (district_code, district_name, state_code) values (305,	'Nagaon',	18);
insert into districts (district_code, district_name, state_code) values (323,	'Nalbari',	18);
insert into districts (district_code, district_name, state_code) values (311,	'Sivasagar',	18);
insert into districts (district_code, district_name, state_code) values (306,	'Sonitpur',	18);
insert into districts (district_code, district_name, state_code) values (961,	'South Salamara-Mankachar',	18);
insert into districts (district_code, district_name, state_code) values (309,	'Tinsukia',	18);
insert into districts (district_code, district_name, state_code) values (326,	'Udalguri',	18);
insert into districts (district_code, district_name, state_code) values (962,	'West Karbi Anglong',	18);
insert into districts (district_code, district_name, state_code) values (209,	'Araria',	10);
insert into districts (district_code, district_name, state_code) values (240,	'Arwal',	10);
insert into districts (district_code, district_name, state_code) values (235,	'Aurangabad',	10);
insert into districts (district_code, district_name, state_code) values (225,	'Banka',	10);
insert into districts (district_code, district_name, state_code) values (222,	'Begusarai',	10);
insert into districts (district_code, district_name, state_code) values (224,	'Bhagalpur',	10);
insert into districts (district_code, district_name, state_code) values (231,	'Bhojpur',	10);
insert into districts (district_code, district_name, state_code) values (232,	'Buxar',	10);
insert into districts (district_code, district_name, state_code) values (215,	'Darbhanga',	10);
insert into districts (district_code, district_name, state_code) values (236,	'Gaya',	10);
insert into districts (district_code, district_name, state_code) values (217,	'Gopalganj',	10);
insert into districts (district_code, district_name, state_code) values (238,	'Jamui',	10);
insert into districts (district_code, district_name, state_code) values (239,	'Jehanabad',	10);
insert into districts (district_code, district_name, state_code) values (233,	'Kaimur (Bhabua)',	10);
insert into districts (district_code, district_name, state_code) values (212,	'Katihar',	10);
insert into districts (district_code, district_name, state_code) values (223,	'Khagaria',	10);
insert into districts (district_code, district_name, state_code) values (210,	'Kishanganj',	10);
insert into districts (district_code, district_name, state_code) values (227,	'Lakhisarai',	10);
insert into districts (district_code, district_name, state_code) values (213,	'Madhepura',	10);
insert into districts (district_code, district_name, state_code) values (207,	'Madhubani',	10);
insert into districts (district_code, district_name, state_code) values (226,	'Munger',	10);
insert into districts (district_code, district_name, state_code) values (216,	'Muzaffarpur',	10);
insert into districts (district_code, district_name, state_code) values (229,	'Nalanda',	10);
insert into districts (district_code, district_name, state_code) values (237,	'Nawada',	10);
insert into districts (district_code, district_name, state_code) values (203,	'Pashchim Champaran',	10);
insert into districts (district_code, district_name, state_code) values (230,	'Patna',	10);
insert into districts (district_code, district_name, state_code) values (204,	'Purbi Champaran',	10);
insert into districts (district_code, district_name, state_code) values (211,	'Purnia',	10);
insert into districts (district_code, district_name, state_code) values (234,	'Rohtas',	10);
insert into districts (district_code, district_name, state_code) values (214,	'Saharsa',	10);
insert into districts (district_code, district_name, state_code) values (221,	'Samastipur',	10);
insert into districts (district_code, district_name, state_code) values (219,	'Saran',	10);
insert into districts (district_code, district_name, state_code) values (228,	'Sheikhpura',	10);
insert into districts (district_code, district_name, state_code) values (205,	'Sheohar',	10);
insert into districts (district_code, district_name, state_code) values (206,	'Sitamarhi',	10);
insert into districts (district_code, district_name, state_code) values (218,	'Siwan',	10);
insert into districts (district_code, district_name, state_code) values (208,	'Supaul',	10);
insert into districts (district_code, district_name, state_code) values (220,	'Vaishali',	10);
insert into districts (district_code, district_name, state_code) values (055,	'Chandigarh',	04);
insert into districts (district_code, district_name, state_code) values (904,	'Balod',	22);
insert into districts (district_code, district_name, state_code) values (905,	'Baloda Bazar',	22);
insert into districts (district_code, district_name, state_code) values (906,	'Balrampur',	22);
insert into districts (district_code, district_name, state_code) values (414,	'Bastar',	22);
insert into districts (district_code, district_name, state_code) values (907,	'Bemetara',	22);
insert into districts (district_code, district_name, state_code) values (417,	'Bijapur',	22);
insert into districts (district_code, district_name, state_code) values (406,	'Bilaspur',	22);
insert into districts (district_code, district_name, state_code) values (416,	'Dakshin Bastar Dantewada',	22);
insert into districts (district_code, district_name, state_code) values (412,	'Dhamtari',	22);
insert into districts (district_code, district_name, state_code) values (409,	'Durg',	22);
insert into districts (district_code, district_name, state_code) values (908,	'Gariyaband',	22);
insert into districts (district_code, district_name, state_code) values (405,	'Janjgir - Champa',	22);
insert into districts (district_code, district_name, state_code) values (402,	'Jashpur',	22);
insert into districts (district_code, district_name, state_code) values (407,	'Kabeerdham',	22);
insert into districts (district_code, district_name, state_code) values (909,	'Kondagaon',	22);
insert into districts (district_code, district_name, state_code) values (404,	'Korba',	22);
insert into districts (district_code, district_name, state_code) values (400,	'Koriya',	22);
insert into districts (district_code, district_name, state_code) values (411,	'Mahasamund',	22);
insert into districts (district_code, district_name, state_code) values (910,	'Mungeli',	22);
insert into districts (district_code, district_name, state_code) values (415,	'Narayanpur',	22);
insert into districts (district_code, district_name, state_code) values (403,	'Raigarh',	22);
insert into districts (district_code, district_name, state_code) values (410,	'Raipur',	22);
insert into districts (district_code, district_name, state_code) values (408,	'Rajnandgaon',	22);
insert into districts (district_code, district_name, state_code) values (911,	'Sukma',	22);
insert into districts (district_code, district_name, state_code) values (912,	'Surajpur',	22);
insert into districts (district_code, district_name, state_code) values (401,	'Surguja',	22);
insert into districts (district_code, district_name, state_code) values (413,	'Uttar Bastar Kanker',	22);
insert into districts (district_code, district_name, state_code) values (496,	'Dadra and Nagar Haveli',	26);
insert into districts (district_code, district_name, state_code) values (495,	'Daman',	25);
insert into districts (district_code, district_name, state_code) values (494,	'Diu',	25);
insert into districts (district_code, district_name, state_code) values (585,	'North Goa',	30);
insert into districts (district_code, district_name, state_code) values (586,	'South Goa',	30);
insert into districts (district_code, district_name, state_code) values (474,	'Ahmadabad',	24);
insert into districts (district_code, district_name, state_code) values (480,	'Amreli',	24);
insert into districts (district_code, district_name, state_code) values (482,	'Anand',	24);
insert into districts (district_code, district_name, state_code) values (922,	'Arvalli',	24);
insert into districts (district_code, district_name, state_code) values (469,	'Banas Kantha',	24);
insert into districts (district_code, district_name, state_code) values (488,	'Bharuch',	24);
insert into districts (district_code, district_name, state_code) values (481,	'Bhavnagar',	24);
insert into districts (district_code, district_name, state_code) values (923,	'Botad',	24);
insert into districts (district_code, district_name, state_code) values (920,	'Chhota Udepur',	24);
insert into districts (district_code, district_name, state_code) values (925,	'Devbhoomi Dwarka',	24);
insert into districts (district_code, district_name, state_code) values (485,	'Dohad',	24);
insert into districts (district_code, district_name, state_code) values (473,	'Gandhinagar',	24);
insert into districts (district_code, district_name, state_code) values (921,	'Gir Somnath',	24);
insert into districts (district_code, district_name, state_code) values (477,	'Jamnagar',	24);
insert into districts (district_code, district_name, state_code) values (479,	'Junagadh',	24);
insert into districts (district_code, district_name, state_code) values (468,	'Kachchh',	24);
insert into districts (district_code, district_name, state_code) values (483,	'Kheda',	24);
insert into districts (district_code, district_name, state_code) values (471,	'Mahesana',	24);
insert into districts (district_code, district_name, state_code) values (926,	'Mahisagar',	24);
insert into districts (district_code, district_name, state_code) values (924,	'Morbi',	24);
insert into districts (district_code, district_name, state_code) values (487,	'Narmada',	24);
insert into districts (district_code, district_name, state_code) values (490,	'Navsari',	24);
insert into districts (district_code, district_name, state_code) values (484,	'Panch Mahals',	24);
insert into districts (district_code, district_name, state_code) values (470,	'Patan',	24);
insert into districts (district_code, district_name, state_code) values (478,	'Porbandar',	24);
insert into districts (district_code, district_name, state_code) values (476,	'Rajkot',	24);
insert into districts (district_code, district_name, state_code) values (472,	'Sabar Kantha',	24);
insert into districts (district_code, district_name, state_code) values (492,	'Surat',	24);
insert into districts (district_code, district_name, state_code) values (475,	'Surendranagar',	24);
insert into districts (district_code, district_name, state_code) values (493,	'Tapi',	24);
insert into districts (district_code, district_name, state_code) values (489,	'The Dangs',	24);
insert into districts (district_code, district_name, state_code) values (486,	'Vadodara',	24);
insert into districts (district_code, district_name, state_code) values (491,	'Valsad',	24);
insert into districts (district_code, district_name, state_code) values (070,	'Ambala',	06);
insert into districts (district_code, district_name, state_code) values (081,	'Bhiwani',	06);
insert into districts (district_code, district_name, state_code) values (965,	'Charkhi Dadri',	06);
insert into districts (district_code, district_name, state_code) values (088,	'Faridabad',	06);
insert into districts (district_code, district_name, state_code) values (078,	'Fatehabad',	06);
insert into districts (district_code, district_name, state_code) values (086,	'Gurgaon',	06);
insert into districts (district_code, district_name, state_code) values (080,	'Hisar',	06);
insert into districts (district_code, district_name, state_code) values (083,	'Jhajjar',	06);
insert into districts (district_code, district_name, state_code) values (077,	'Jind',	06);
insert into districts (district_code, district_name, state_code) values (073,	'Kaithal',	06);
insert into districts (district_code, district_name, state_code) values (074,	'Karnal',	06);
insert into districts (district_code, district_name, state_code) values (072,	'Kurukshetra',	06);
insert into districts (district_code, district_name, state_code) values (084,	'Mahendragarh',	06);
insert into districts (district_code, district_name, state_code) values (087,	'Mewat',	06);
insert into districts (district_code, district_name, state_code) values (089,	'Palwal',	06);
insert into districts (district_code, district_name, state_code) values (069,	'Panchkula',	06);
insert into districts (district_code, district_name, state_code) values (075,	'Panipat',	06);
insert into districts (district_code, district_name, state_code) values (085,	'Rewari',	06);
insert into districts (district_code, district_name, state_code) values (082,	'Rohtak',	06);
insert into districts (district_code, district_name, state_code) values (079,	'Sirsa',	06);
insert into districts (district_code, district_name, state_code) values (076,	'Sonipat',	06);
insert into districts (district_code, district_name, state_code) values (071,	'Yamunanagar',	06);
insert into districts (district_code, district_name, state_code) values (030,	'Bilaspur',	02);
insert into districts (district_code, district_name, state_code) values (023,	'Chamba',	02);
insert into districts (district_code, district_name, state_code) values (028,	'Hamirpur',	02);
insert into districts (district_code, district_name, state_code) values (024,	'Kangra',	02);
insert into districts (district_code, district_name, state_code) values (034,	'Kinnaur',	02);
insert into districts (district_code, district_name, state_code) values (026,	'Kullu',	02);
insert into districts (district_code, district_name, state_code) values (025,	'Lahul Spiti',	02);
insert into districts (district_code, district_name, state_code) values (027,	'Mandi',	02);
insert into districts (district_code, district_name, state_code) values (033,	'Shimla',	02);
insert into districts (district_code, district_name, state_code) values (032,	'Sirmaur',	02);
insert into districts (district_code, district_name, state_code) values (031,	'Solan',	02);
insert into districts (district_code, district_name, state_code) values (029,	'Una',	02);
insert into districts (district_code, district_name, state_code) values (014,	'Anantnag',	01);
insert into districts (district_code, district_name, state_code) values (002,	'Badgam',	01);
insert into districts (district_code, district_name, state_code) values (009,	'Bandipore',	01);
insert into districts (district_code, district_name, state_code) values (008,	'Baramula',	01);
insert into districts (district_code, district_name, state_code) values (016,	'Doda',	01);
insert into districts (district_code, district_name, state_code) values (011,	'Ganderbal',	01);
insert into districts (district_code, district_name, state_code) values (021,	'Jammu',	01);
insert into districts (district_code, district_name, state_code) values (004,	'Kargil',	01);
insert into districts (district_code, district_name, state_code) values (007,	'Kathua',	01);
insert into districts (district_code, district_name, state_code) values (018,	'Kishtwar',	01);
insert into districts (district_code, district_name, state_code) values (015,	'Kulgam',	01);
insert into districts (district_code, district_name, state_code) values (001,	'Kupwara',	01);
insert into districts (district_code, district_name, state_code) values (003,	'Leh(Ladakh)',	01);
insert into districts (district_code, district_name, state_code) values (012,	'Pulwama',	01);
insert into districts (district_code, district_name, state_code) values (005,	'Punch',	01);
insert into districts (district_code, district_name, state_code) values (006,	'Rajouri',	01);
insert into districts (district_code, district_name, state_code) values (017,	'Ramban',	01);
insert into districts (district_code, district_name, state_code) values (020,	'Reasi',	01);
insert into districts (district_code, district_name, state_code) values (022,	'Samba',	01);
insert into districts (district_code, district_name, state_code) values (013,	'Shupiyan',	01);
insert into districts (district_code, district_name, state_code) values (010,	'Srinagar',	01);
insert into districts (district_code, district_name, state_code) values (019,	'Udhampur',	01);
insert into districts (district_code, district_name, state_code) values (355,	'Bokaro',	20);
insert into districts (district_code, district_name, state_code) values (347,	'Chatra',	20);
insert into districts (district_code, district_name, state_code) values (350,	'Deoghar',	20);
insert into districts (district_code, district_name, state_code) values (354,	'Dhanbad',	20);
insert into districts (district_code, district_name, state_code) values (362,	'Dumka',	20);
insert into districts (district_code, district_name, state_code) values (346,	'Garhwa',	20);
insert into districts (district_code, district_name, state_code) values (349,	'Giridih',	20);
insert into districts (district_code, district_name, state_code) values (351,	'Godda',	20);
insert into districts (district_code, district_name, state_code) values (366,	'Gumla',	20);
insert into districts (district_code, district_name, state_code) values (360,	'Hazaribagh',	20);
insert into districts (district_code, district_name, state_code) values (363,	'Jamtara',	20);
insert into districts (district_code, district_name, state_code) values (365,	'Khunti',	20);
insert into districts (district_code, district_name, state_code) values (348,	'Kodarma',	20);
insert into districts (district_code, district_name, state_code) values (359,	'Latehar',	20);
insert into districts (district_code, district_name, state_code) values (356,	'Lohardaga',	20);
insert into districts (district_code, district_name, state_code) values (353,	'Pakur',	20);
insert into districts (district_code, district_name, state_code) values (358,	'Palamu',	20);
insert into districts (district_code, district_name, state_code) values (368,	'Pashchimi Singhbhum',	20);
insert into districts (district_code, district_name, state_code) values (357,	'Purbi Singhbhum',	20);
insert into districts (district_code, district_name, state_code) values (361,	'Ramgarh',	20);
insert into districts (district_code, district_name, state_code) values (364,	'Ranchi',	20);
insert into districts (district_code, district_name, state_code) values (352,	'Sahibganj',	20);
insert into districts (district_code, district_name, state_code) values (369,	'Saraikela-Kharsawan',	20);
insert into districts (district_code, district_name, state_code) values (367,	'Simdega',	20);
insert into districts (district_code, district_name, state_code) values (556,	'Bagalkot',	29);
insert into districts (district_code, district_name, state_code) values (572,	'Bangalore',	29);
insert into districts (district_code, district_name, state_code) values (583,	'Bangalore Rural',	29);
insert into districts (district_code, district_name, state_code) values (555,	'Belgaum',	29);
insert into districts (district_code, district_name, state_code) values (565,	'Bellary',	29);
insert into districts (district_code, district_name, state_code) values (558,	'Bidar',	29);
insert into districts (district_code, district_name, state_code) values (557,	'Bijapur',	29);
insert into districts (district_code, district_name, state_code) values (578,	'Chamarajanagar',	29);
insert into districts (district_code, district_name, state_code) values (582,	'Chikkaballapura',	29);
insert into districts (district_code, district_name, state_code) values (570,	'Chikmagalur',	29);
insert into districts (district_code, district_name, state_code) values (566,	'Chitradurga',	29);
insert into districts (district_code, district_name, state_code) values (575,	'Dakshina Kannada',	29);
insert into districts (district_code, district_name, state_code) values (567,	'Davanagere',	29);
insert into districts (district_code, district_name, state_code) values (562,	'Dharwad',	29);
insert into districts (district_code, district_name, state_code) values (561,	'Gadag',	29);
insert into districts (district_code, district_name, state_code) values (579,	'Gulbarga',	29);
insert into districts (district_code, district_name, state_code) values (574,	'Hassan',	29);
insert into districts (district_code, district_name, state_code) values (564,	'Haveri',	29);
insert into districts (district_code, district_name, state_code) values (576,	'Kodagu',	29);
insert into districts (district_code, district_name, state_code) values (581,	'Kolar',	29);
insert into districts (district_code, district_name, state_code) values (560,	'Koppal',	29);
insert into districts (district_code, district_name, state_code) values (573,	'Mandya',	29);
insert into districts (district_code, district_name, state_code) values (577,	'Mysore',	29);
insert into districts (district_code, district_name, state_code) values (559,	'Raichur',	29);
insert into districts (district_code, district_name, state_code) values (584,	'Ramanagara',	29);
insert into districts (district_code, district_name, state_code) values (568,	'Shimoga',	29);
insert into districts (district_code, district_name, state_code) values (571,	'Tumkur',	29);
insert into districts (district_code, district_name, state_code) values (569,	'Udupi',	29);
insert into districts (district_code, district_name, state_code) values (563,	'Uttara Kannada',	29);
insert into districts (district_code, district_name, state_code) values (580,	'Yadgir',	29);
insert into districts (district_code, district_name, state_code) values (598,	'Alappuzha',	32);
insert into districts (district_code, district_name, state_code) values (595,	'Ernakulam',	32);
insert into districts (district_code, district_name, state_code) values (596,	'Idukki',	32);
insert into districts (district_code, district_name, state_code) values (589,	'Kannur',	32);
insert into districts (district_code, district_name, state_code) values (588,	'Kasaragod',	32);
insert into districts (district_code, district_name, state_code) values (600,	'Kollam',	32);
insert into districts (district_code, district_name, state_code) values (597,	'Kottayam',	32);
insert into districts (district_code, district_name, state_code) values (591,	'Kozhikode',	32);
insert into districts (district_code, district_name, state_code) values (592,	'Malappuram',	32);
insert into districts (district_code, district_name, state_code) values (593,	'Palakkad',	32);
insert into districts (district_code, district_name, state_code) values (599,	'Pathanamthitta',	32);
insert into districts (district_code, district_name, state_code) values (601,	'Thiruvananthapuram',	32);
insert into districts (district_code, district_name, state_code) values (594,	'Thrissur',	32);
insert into districts (district_code, district_name, state_code) values (590,	'Wayanad',	32);
insert into districts (district_code, district_name, state_code) values (587,	'Lakshadweep',	31);
insert into districts (district_code, district_name, state_code) values (913, '      	Agar Malwa',	23);
insert into districts (district_code, district_name, state_code) values (465,	'Alirajpur',	23);
insert into districts (district_code, district_name, state_code) values (461,	'Anuppur',	23);
insert into districts (district_code, district_name, state_code) values (459,	'Ashoknagar',	23);
insert into districts (district_code, district_name, state_code) values (457,	'Balaghat',	23);
insert into districts (district_code, district_name, state_code) values (441,	'Barwani',	23);
insert into districts (district_code, district_name, state_code) values (447,	'Betul',	23);
insert into districts (district_code, district_name, state_code) values (420,	'Bhind',	23);
insert into districts (district_code, district_name, state_code) values (444,	'Bhopal',	23);
insert into districts (district_code, district_name, state_code) values (467,	'Burhanpur',	23);
insert into districts (district_code, district_name, state_code) values (425,	'Chhatarpur',	23);
insert into districts (district_code, district_name, state_code) values (455,	'Chhindwara',	23);
insert into districts (district_code, district_name, state_code) values (428,	'Damoh',	23);
insert into districts (district_code, district_name, state_code) values (422,	'Datia',	23);
insert into districts (district_code, district_name, state_code) values (437,	'Dewas',	23);
insert into districts (district_code, district_name, state_code) values (438,	'Dhar',	23);
insert into districts (district_code, district_name, state_code) values (453,	'Dindori',	23);
insert into districts (district_code, district_name, state_code) values (458,	'Guna',	23);
insert into districts (district_code, district_name, state_code) values (421,	'Gwalior',	23);
insert into districts (district_code, district_name, state_code) values (448,	'Harda',	23);
insert into districts (district_code, district_name, state_code) values (449,	'Hoshangabad',	23);
insert into districts (district_code, district_name, state_code) values (439,	'Indore',	23);
insert into districts (district_code, district_name, state_code) values (451,	'Jabalpur',	23);
insert into districts (district_code, district_name, state_code) values (464,	'Jhabua',	23);
insert into districts (district_code, district_name, state_code) values (450,	'Katni',	23);
insert into districts (district_code, district_name, state_code) values (466,	'Khandwa (East Nimar)',	23);
insert into districts (district_code, district_name, state_code) values (440,	'Khargone (West Nimar)',	23);
insert into districts (district_code, district_name, state_code) values (454,	'Mandla',	23);
insert into districts (district_code, district_name, state_code) values (433,	'Mandsaur',	23);
insert into districts (district_code, district_name, state_code) values (419,	'Morena',	23);
insert into districts (district_code, district_name, state_code) values (452,	'Narsimhapur',	23);
insert into districts (district_code, district_name, state_code) values (432,	'Neemuch',	23);
insert into districts (district_code, district_name, state_code) values (426,	'Panna',	23);
insert into districts (district_code, district_name, state_code) values (446,	'Raisen',	23);
insert into districts (district_code, district_name, state_code) values (442,	'Rajgarh',	23);
insert into districts (district_code, district_name, state_code) values (434,	'Ratlam',	23);
insert into districts (district_code, district_name, state_code) values (430,	'Rewa',	23);
insert into districts (district_code, district_name, state_code) values (427,	'Sagar',	23);
insert into districts (district_code, district_name, state_code) values (429,	'Satna',	23);
insert into districts (district_code, district_name, state_code) values (445,	'Sehore',	23);
insert into districts (district_code, district_name, state_code) values (456,	'Seoni',	23);
insert into districts (district_code, district_name, state_code) values (460,	'Shahdol',	23);
insert into districts (district_code, district_name, state_code) values (436,	'Shajapur',	23);
insert into districts (district_code, district_name, state_code) values (418,	'Sheopur',	23);
insert into districts (district_code, district_name, state_code) values (423,	'Shivpuri',	23);
insert into districts (district_code, district_name, state_code) values (462,	'Sidhi',	23);
insert into districts (district_code, district_name, state_code) values (463,	'Singrauli',	23);
insert into districts (district_code, district_name, state_code) values (424,	'Tikamgarh',	23);
insert into districts (district_code, district_name, state_code) values (435,	'Ujjain',	23);
insert into districts (district_code, district_name, state_code) values (431,	'Umaria',	23);
insert into districts (district_code, district_name, state_code) values (443,	'Vidisha',	23);
insert into districts (district_code, district_name, state_code) values (522,	'Ahmadnagar',	27);
insert into districts (district_code, district_name, state_code) values (501,	'Akola',	27);
insert into districts (district_code, district_name, state_code) values (503,	'Amravati',	27);
insert into districts (district_code, district_name, state_code) values (515,	'Aurangabad',	27);
insert into districts (district_code, district_name, state_code) values (506,	'Bhandara',	27);
insert into districts (district_code, district_name, state_code) values (523,	'Bid',	27);
insert into districts (district_code, district_name, state_code) values (500,	'Buldana',	27);
insert into districts (district_code, district_name, state_code) values (509,	'Chandrapur',	27);
insert into districts (district_code, district_name, state_code) values (498,	'Dhule',	27);
insert into districts (district_code, district_name, state_code) values (508,	'Gadchiroli',	27);
insert into districts (district_code, district_name, state_code) values (507,	'Gondiya',	27);
insert into districts (district_code, district_name, state_code) values (512,	'Hingoli',	27);
insert into districts (district_code, district_name, state_code) values (499,	'Jalgaon',	27);
insert into districts (district_code, district_name, state_code) values (514,	'Jalna',	27);
insert into districts (district_code, district_name, state_code) values (530,	'Kolhapur',	27);
insert into districts (district_code, district_name, state_code) values (524,	'Latur',	27);
insert into districts (district_code, district_name, state_code) values (519,	'Mumbai',	27);
insert into districts (district_code, district_name, state_code) values (518,	'Mumbai Suburban',	27);
insert into districts (district_code, district_name, state_code) values (505,	'Nagpur',	27);
insert into districts (district_code, district_name, state_code) values (511,	'Nanded',	27);
insert into districts (district_code, district_name, state_code) values (497,	'Nandurbar',	27);
insert into districts (district_code, district_name, state_code) values (516,	'Nashik',	27);
insert into districts (district_code, district_name, state_code) values (525,	'Osmanabad',	27);
insert into districts (district_code, district_name, state_code) values (919,	'Palghar',	27);
insert into districts (district_code, district_name, state_code) values (513,	'Parbhani',	27);
insert into districts (district_code, district_name, state_code) values (521,	'Pune',	27);
insert into districts (district_code, district_name, state_code) values (520,	'Raigarh',	27);
insert into districts (district_code, district_name, state_code) values (528,	'Ratnagiri',	27);
insert into districts (district_code, district_name, state_code) values (531,	'Sangli',	27);
insert into districts (district_code, district_name, state_code) values (527,	'Satara',	27);
insert into districts (district_code, district_name, state_code) values (529,	'Sindhudurg',	27);
insert into districts (district_code, district_name, state_code) values (526,	'Solapur',	27);
insert into districts (district_code, district_name, state_code) values (517,	'Thane',	27);
insert into districts (district_code, district_name, state_code) values (504,	'Wardha',	27);
insert into districts (district_code, district_name, state_code) values (502,	'Washim',	27);
insert into districts (district_code, district_name, state_code) values (510,	'Yavatmal',	27);
insert into districts (district_code, district_name, state_code) values (275,	'Bishnupur',	14);
insert into districts (district_code, district_name, state_code) values (280,	'Chandel',	14);
insert into districts (district_code, district_name, state_code) values (274,	'Churachandpur',	14);
insert into districts (district_code, district_name, state_code) values (278,	'Imphal East',	14);
insert into districts (district_code, district_name, state_code) values (277,	'Imphal West',	14);
insert into districts (district_code, district_name, state_code) values (966,	'Jiribam',	14);
insert into districts (district_code, district_name, state_code) values (967,	'Kakching',	14);
insert into districts (district_code, district_name, state_code) values (968,	'Kamjong',	14);
insert into districts (district_code, district_name, state_code) values (969,	'Kangpokpi',	14);
insert into districts (district_code, district_name, state_code) values (970,	'Noney',	14);
insert into districts (district_code, district_name, state_code) values (971,	'Pherzawl',	14);
insert into districts (district_code, district_name, state_code) values (272,	'Senapati',	14);
insert into districts (district_code, district_name, state_code) values (273,	'Tamenglong',	14);
insert into districts (district_code, district_name, state_code) values (972,	'Tengnoupal',	14);
insert into districts (district_code, district_name, state_code) values (276,	'Thoubal',	14);
insert into districts (district_code, district_name, state_code) values (279,	'Ukhrul',	14);
insert into districts (district_code, district_name, state_code) values (294,	'East Garo Hills',	17);
insert into districts (district_code, district_name, state_code) values (973,	'East Jaintia Hills',	17);
insert into districts (district_code, district_name, state_code) values (298,	'East Khasi Hills',	17);
insert into districts (district_code, district_name, state_code) values (299,	'Jaintia Hills',	17);
insert into districts (district_code, district_name, state_code) values (974,	'North Garo Hills',	17);
insert into districts (district_code, district_name, state_code) values (297,	'Ribhoi',	17);
insert into districts (district_code, district_name, state_code) values (295,	'South Garo Hills',	17);
insert into districts (district_code, district_name, state_code) values (975,	'South West Garo Hills',	17);
insert into districts (district_code, district_name, state_code) values (976,	'South West Khasi Hills',	17);
insert into districts (district_code, district_name, state_code) values (293,	'West Garo Hills',	17);
insert into districts (district_code, district_name, state_code) values (977,	'West Jaintia Hills',	17);
insert into districts (district_code, district_name, state_code) values (296,	'West Khasi Hills',	17);
insert into districts (district_code, district_name, state_code) values (283,	'Aizawl',	15);
insert into districts (district_code, district_name, state_code) values (284,	'Champhai',	15);
insert into districts (district_code, district_name, state_code) values (282,	'Kolasib',	15);
insert into districts (district_code, district_name, state_code) values (287,	'Lawngtlai',	15);
insert into districts (district_code, district_name, state_code) values (286,	'Lunglei',	15);
insert into districts (district_code, district_name, state_code) values (281,	'Mamit',	15);
insert into districts (district_code, district_name, state_code) values (288,	'Saiha',	15);
insert into districts (district_code, district_name, state_code) values (285,	'Serchhip',	15);
insert into districts (district_code, district_name, state_code) values (265,	'Dimapur',	13);
insert into districts (district_code, district_name, state_code) values (269,	'Kiphire',	13);
insert into districts (district_code, district_name, state_code) values (270,	'Kohima',	13);
insert into districts (district_code, district_name, state_code) values (268,	'Longleng',	13);
insert into districts (district_code, district_name, state_code) values (262,	'Mokokchung',	13);
insert into districts (district_code, district_name, state_code) values (261,	'Mon',	13);
insert into districts (district_code, district_name, state_code) values (271,	'Peren',	13);
insert into districts (district_code, district_name, state_code) values (266,	'Phek',	13);
insert into districts (district_code, district_name, state_code) values (267,	'Tuensang',	13);
insert into districts (district_code, district_name, state_code) values (264,	'Wokha',	13);
insert into districts (district_code, district_name, state_code) values (263,	'Zunheboto',	13);
insert into districts (district_code, district_name, state_code) values (095,	'Central',	07);
insert into districts (district_code, district_name, state_code) values (093,	'East',	07);
insert into districts (district_code, district_name, state_code) values (094,	'New Delhi',	07);
insert into districts (district_code, district_name, state_code) values (091,	'North',	07);
insert into districts (district_code, district_name, state_code) values (092,	'North East',	07);
insert into districts (district_code, district_name, state_code) values (090,	'North West',	07);
insert into districts (district_code, district_name, state_code) values (963,	'Shahdara',	07);
insert into districts (district_code, district_name, state_code) values (098,	'South',	07);
insert into districts (district_code, district_name, state_code) values (964,	'South East Delhi',	07);
insert into districts (district_code, district_name, state_code) values (097,	'South West',	07);
insert into districts (district_code, district_name, state_code) values (096,	'West',	07);
insert into districts (district_code, district_name, state_code) values (384,	'Anugul',	21);
insert into districts (district_code, district_name, state_code) values (393,	'Balangir',	21);
insert into districts (district_code, district_name, state_code) values (377,	'Baleshwar',	21);
insert into districts (district_code, district_name, state_code) values (370,	'Bargarh',	21);
insert into districts (district_code, district_name, state_code) values (391,	'Baudh',	21);
insert into districts (district_code, district_name, state_code) values (378,	'Bhadrak',	21);
insert into districts (district_code, district_name, state_code) values (381,	'Cuttack',	21);
insert into districts (district_code, district_name, state_code) values (373,	'Debagarh',	21);
insert into districts (district_code, district_name, state_code) values (383,	'Dhenkanal',	21);
insert into districts (district_code, district_name, state_code) values (389,	'Gajapati',	21);
insert into districts (district_code, district_name, state_code) values (388,	'Ganjam',	21);
insert into districts (district_code, district_name, state_code) values (380,	'Jagatsinghapur',	21);
insert into districts (district_code, district_name, state_code) values (382,	'Jajapur',	21);
insert into districts (district_code, district_name, state_code) values (371,	'Jharsuguda',	21);
insert into districts (district_code, district_name, state_code) values (395,	'Kalahandi',	21);
insert into districts (district_code, district_name, state_code) values (390,	'Kandhamal',	21);
insert into districts (district_code, district_name, state_code) values (379,	'Kendrapara',	21);
insert into districts (district_code, district_name, state_code) values (375,	'Kendujhar',	21);
insert into districts (district_code, district_name, state_code) values (386,	'Khordha',	21);
insert into districts (district_code, district_name, state_code) values (398,	'Koraput',	21);
insert into districts (district_code, district_name, state_code) values (399,	'Malkangiri',	21);
insert into districts (district_code, district_name, state_code) values (376,	'Mayurbhanj',	21);
insert into districts (district_code, district_name, state_code) values (397,	'Nabarangapur',	21);
insert into districts (district_code, district_name, state_code) values (385,	'Nayagarh',	21);
insert into districts (district_code, district_name, state_code) values (394,	'Nuapada',	21);
insert into districts (district_code, district_name, state_code) values (387,	'Puri',	21);
insert into districts (district_code, district_name, state_code) values (396,	'Rayagada',	21);
insert into districts (district_code, district_name, state_code) values (372,	'Sambalpur',	21);
insert into districts (district_code, district_name, state_code) values (392,	'Subarnapur',	21);
insert into districts (district_code, district_name, state_code) values (374,	'Sundargarh',	21);
insert into districts (district_code, district_name, state_code) values (637,	'Karaikal',	34);
insert into districts (district_code, district_name, state_code) values (636,	'Mahe',	34);
insert into districts (district_code, district_name, state_code) values (635,	'Puducherry',	34);
insert into districts (district_code, district_name, state_code) values (634,	'Yanam',	34);
insert into districts (district_code, district_name, state_code) values (049,	'Amritsar',	03);
insert into districts (district_code, district_name, state_code) values (054,	'Barnala',	03);
insert into districts (district_code, district_name, state_code) values (046,	'Bathinda',	03);
insert into districts (district_code, district_name, state_code) values (045,	'Faridkot',	03);
insert into districts (district_code, district_name, state_code) values (040,	'Fatehgarh Sahib',	03);
insert into districts (district_code, district_name, state_code) values (978,	'Fazilka',	03);
insert into districts (district_code, district_name, state_code) values (043,	'Firozpur',	03);
insert into districts (district_code, district_name, state_code) values (035,	'Gurdaspur',	03);
insert into districts (district_code, district_name, state_code) values (038,	'Hoshiarpur',	03);
insert into districts (district_code, district_name, state_code) values (037,	'Jalandhar',	03);
insert into districts (district_code, district_name, state_code) values (036,	'Kapurthala',	03);
insert into districts (district_code, district_name, state_code) values (041,	'Ludhiana',	03);
insert into districts (district_code, district_name, state_code) values (047,	'Mansa',	03);
insert into districts (district_code, district_name, state_code) values (042,	'Moga',	03);
insert into districts (district_code, district_name, state_code) values (044,	'Muktsar',	03);
insert into districts (district_code, district_name, state_code) values (979,	'Pathankot',	03);
insert into districts (district_code, district_name, state_code) values (048,	'Patiala',	03);
insert into districts (district_code, district_name, state_code) values (051,	'Rupnagar',	03);
insert into districts (district_code, district_name, state_code) values (052,	'Sahibzada Ajit Singh Nagar',	03);
insert into districts (district_code, district_name, state_code) values (053,	'Sangrur',	03);
insert into districts (district_code, district_name, state_code) values (039,	'Shahid Bhagat Singh Nagar',	03);
insert into districts (district_code, district_name, state_code) values (050,	'Tarn Taran',	03);
insert into districts (district_code, district_name, state_code) values (119,	'Ajmer',	08);
insert into districts (district_code, district_name, state_code) values (104,	'Alwar',	08);
insert into districts (district_code, district_name, state_code) values (125,	'Banswara',	08);
insert into districts (district_code, district_name, state_code) values (128,	'Baran',	08);
insert into districts (district_code, district_name, state_code) values (115,	'Barmer',	08);
insert into districts (district_code, district_name, state_code) values (105,	'Bharatpur',	08);
insert into districts (district_code, district_name, state_code) values (122,	'Bhilwara',	08);
insert into districts (district_code, district_name, state_code) values (101,	'Bikaner',	08);
insert into districts (district_code, district_name, state_code) values (121,	'Bundi',	08);
insert into districts (district_code, district_name, state_code) values (126,	'Chittaurgarh',	08);
insert into districts (district_code, district_name, state_code) values (102,	'Churu',	08);
insert into districts (district_code, district_name, state_code) values (109,	'Dausa',	08);
insert into districts (district_code, district_name, state_code) values (106,	'Dhaulpur',	08);
insert into districts (district_code, district_name, state_code) values (124,	'Dungarpur',	08);
insert into districts (district_code, district_name, state_code) values (100,	'Hanumangarh',	08);
insert into districts (district_code, district_name, state_code) values (110,	'Jaipur',	08);
insert into districts (district_code, district_name, state_code) values (114,	'Jaisalmer',	08);
insert into districts (district_code, district_name, state_code) values (116,	'Jalor',	08);
insert into districts (district_code, district_name, state_code) values (129,	'Jhalawar',	08);
insert into districts (district_code, district_name, state_code) values (103,	'Jhunjhunun',	08);
insert into districts (district_code, district_name, state_code) values (113,	'Jodhpur',	08);
insert into districts (district_code, district_name, state_code) values (107,	'Karauli',	08);
insert into districts (district_code, district_name, state_code) values (127,	'Kota',	08);
insert into districts (district_code, district_name, state_code) values (112,	'Nagaur',	08);
insert into districts (district_code, district_name, state_code) values (118,	'Pali',	08);
insert into districts (district_code, district_name, state_code) values (131,	'Pratapgarh',	08);
insert into districts (district_code, district_name, state_code) values (123,	'Rajsamand',	08);
insert into districts (district_code, district_name, state_code) values (108,	'Sawai Madhopur',	08);
insert into districts (district_code, district_name, state_code) values (111,	'Sikar',	08);
insert into districts (district_code, district_name, state_code) values (117,	'Sirohi',	08);
insert into districts (district_code, district_name, state_code) values (099,	'Sri Ganganagar',	08);
insert into districts (district_code, district_name, state_code) values (120,	'Tonk',	08);
insert into districts (district_code, district_name, state_code) values (130,	'Udaipur',	08);
insert into districts (district_code, district_name, state_code) values (244,	'East District',	11);
insert into districts (district_code, district_name, state_code) values (241,	'North  District',	11);
insert into districts (district_code, district_name, state_code) values (243,	'South District',	11);
insert into districts (district_code, district_name, state_code) values (242,	'West District',	11);
insert into districts (district_code, district_name, state_code) values (616,	'Ariyalur',	33);
insert into districts (district_code, district_name, state_code) values (603,	'Chennai',	33);
insert into districts (district_code, district_name, state_code) values (632,	'Coimbatore',	33);
insert into districts (district_code, district_name, state_code) values (617,	'Cuddalore',	33);
insert into districts (district_code, district_name, state_code) values (630,	'Dharmapuri',	33);
insert into districts (district_code, district_name, state_code) values (612,	'Dindigul',	33);
insert into districts (district_code, district_name, state_code) values (610,	'Erode',	33);
insert into districts (district_code, district_name, state_code) values (604,	'Kancheepuram',	33);
insert into districts (district_code, district_name, state_code) values (629,	'Kanniyakumari',	33);
insert into districts (district_code, district_name, state_code) values (613,	'Karur',	33);
insert into districts (district_code, district_name, state_code) values (631,	'Krishnagiri',	33);
insert into districts (district_code, district_name, state_code) values (623,	'Madurai',	33);
insert into districts (district_code, district_name, state_code) values (618,	'Nagapattinam',	33);
insert into districts (district_code, district_name, state_code) values (609,	'Namakkal',	33);
insert into districts (district_code, district_name, state_code) values (615,	'Perambalur',	33);
insert into districts (district_code, district_name, state_code) values (621,	'Pudukkottai',	33);
insert into districts (district_code, district_name, state_code) values (626,	'Ramanathapuram',	33);
insert into districts (district_code, district_name, state_code) values (608,	'Salem',	33);
insert into districts (district_code, district_name, state_code) values (622,	'Sivaganga',	33);
insert into districts (district_code, district_name, state_code) values (620,	'Thanjavur',	33);
insert into districts (district_code, district_name, state_code) values (611,	'The Nilgiris',	33);
insert into districts (district_code, district_name, state_code) values (624,	'Theni',	33);
insert into districts (district_code, district_name, state_code) values (602,	'Thiruvallur',	33);
insert into districts (district_code, district_name, state_code) values (619,	'Thiruvarur',	33);
insert into districts (district_code, district_name, state_code) values (627,	'Thoothukkudi',	33);
insert into districts (district_code, district_name, state_code) values (614,	'Tiruchirappalli',	33);
insert into districts (district_code, district_name, state_code) values (628,	'Tirunelveli',	33);
insert into districts (district_code, district_name, state_code) values (633,	'Tiruppur',	33);
insert into districts (district_code, district_name, state_code) values (606,	'Tiruvannamalai',	33);
insert into districts (district_code, district_name, state_code) values (605,	'Vellore',	33);
insert into districts (district_code, district_name, state_code) values (607,	'Viluppuram',	33);
insert into districts (district_code, district_name, state_code) values (625,	'Virudhunagar',	33);
insert into districts (district_code, district_name, state_code) values (532,	'Adilabad',	36);
insert into districts (district_code, district_name, state_code) values (927,	'Bhadradri',	36);
insert into districts (district_code, district_name, state_code) values (536,	'Hyderabad',	36);
insert into districts (district_code, district_name, state_code) values (928,	'Jagtial',	36);
insert into districts (district_code, district_name, state_code) values (929,	'Jangaon',	36);
insert into districts (district_code, district_name, state_code) values (930,	'Jayashankar',	36);
insert into districts (district_code, district_name, state_code) values (931,	'Jogulamba',	36);
insert into districts (district_code, district_name, state_code) values (932,	'Kamareddy',	36);
insert into districts (district_code, district_name, state_code) values (534,	'Karimnagar',	36);
insert into districts (district_code, district_name, state_code) values (541,	'Khammam',	36);
insert into districts (district_code, district_name, state_code) values (933,	'Komaram Bheem',	36);
insert into districts (district_code, district_name, state_code) values (934,	'Mahabubabad',	36);
insert into districts (district_code, district_name, state_code) values (538,	'Mahbubnagar',	36);
insert into districts (district_code, district_name, state_code) values (935,	'Mancherial',	36);
insert into districts (district_code, district_name, state_code) values (535,	'Medak',	36);
insert into districts (district_code, district_name, state_code) values (936,	'Medchal-Malkajgiri',	36);
insert into districts (district_code, district_name, state_code) values (937,	'Nagarkurnool',	36);
insert into districts (district_code, district_name, state_code) values (539,	'Nalgonda',	36);
insert into districts (district_code, district_name, state_code) values (938,	'Nirmal',	36);
insert into districts (district_code, district_name, state_code) values (533,	'Nizamabad',	36);
insert into districts (district_code, district_name, state_code) values (939,	'Peddapalli',	36);
insert into districts (district_code, district_name, state_code) values (940,	'Rajanna',	36);
insert into districts (district_code, district_name, state_code) values (537,	'Rangareddy',	36);
insert into districts (district_code, district_name, state_code) values (941,	'Sangareddy',	36);
insert into districts (district_code, district_name, state_code) values (942,	'Siddipet',	36);
insert into districts (district_code, district_name, state_code) values (943,	'Suryapet',	36);
insert into districts (district_code, district_name, state_code) values (944,	'Vikarabad',	36);
insert into districts (district_code, district_name, state_code) values (945,	'Wanaparthy',	36);
insert into districts (district_code, district_name, state_code) values (946,	'Warangal Rural',	36);
insert into districts (district_code, district_name, state_code) values (947,	'Warangal Urban',	36);
insert into districts (district_code, district_name, state_code) values (948,	'Yadadri',	36);
insert into districts (district_code, district_name, state_code) values (291,	'Dhalai',	16);
insert into districts (district_code, district_name, state_code) values (915,	'Gomati',	16);
insert into districts (district_code, district_name, state_code) values (916,	'Khowai',	16);
insert into districts (district_code, district_name, state_code) values (292,	'North Tripura',	16);
insert into districts (district_code, district_name, state_code) values (917,	'Sepahijala',	16);
insert into districts (district_code, district_name, state_code) values (290,	'South Tripura',	16);
insert into districts (district_code, district_name, state_code) values (918,	'Unakoti',	16);
insert into districts (district_code, district_name, state_code) values (289,	'West Tripura',	16);
insert into districts (district_code, district_name, state_code) values (146,	'Agra',	09);
insert into districts (district_code, district_name, state_code) values (143,	'Aligarh',	09);
insert into districts (district_code, district_name, state_code) values (175,	'Allahabad',	09);
insert into districts (district_code, district_name, state_code) values (178,	'Ambedkar Nagar',	09);
insert into districts (district_code, district_name, state_code) values (900,	'Amethi',	09);
insert into districts (district_code, district_name, state_code) values (137,	'Amroha',	09);
insert into districts (district_code, district_name, state_code) values (162,	'Auraiya',	09);
insert into districts (district_code, district_name, state_code) values (191,	'Azamgarh',	09);
insert into districts (district_code, district_name, state_code) values (139,	'Baghpat',	09);
insert into districts (district_code, district_name, state_code) values (180,	'Bahraich',	09);
insert into districts (district_code, district_name, state_code) values (193,	'Ballia',	09);
insert into districts (district_code, district_name, state_code) values (182,	'Balrampur',	09);
insert into districts (district_code, district_name, state_code) values (170,	'Banda',	09);
insert into districts (district_code, district_name, state_code) values (176,	'Bara Banki',	09);
insert into districts (district_code, district_name, state_code) values (150,	'Bareilly',	09);
insert into districts (district_code, district_name, state_code) values (185,	'Basti',	09);
insert into districts (district_code, district_name, state_code) values (198,	'Bhadohi',	09);
insert into districts (district_code, district_name, state_code) values (134,	'Bijnor',	09);
insert into districts (district_code, district_name, state_code) values (149,	'Budaun',	09);
insert into districts (district_code, district_name, state_code) values (142,	'Bulandshahr',	09);
insert into districts (district_code, district_name, state_code) values (196,	'Chandauli',	09);
insert into districts (district_code, district_name, state_code) values (171,	'Chitrakoot',	09);
insert into districts (district_code, district_name, state_code) values (190,	'Deoria',	09);
insert into districts (district_code, district_name, state_code) values (201,	'Etah',	09);
insert into districts (district_code, district_name, state_code) values (161,	'Etawah',	09);
insert into districts (district_code, district_name, state_code) values (177,	'Faizabad',	09);
insert into districts (district_code, district_name, state_code) values (159,	'Farrukhabad',	09);
insert into districts (district_code, district_name, state_code) values (172,	'Fatehpur',	09);
insert into districts (district_code, district_name, state_code) values (147,	'Firozabad',	09);
insert into districts (district_code, district_name, state_code) values (141,	'Gautam Buddha Nagar',	09);
insert into districts (district_code, district_name, state_code) values (140,	'Ghaziabad',	09);
insert into districts (district_code, district_name, state_code) values (195,	'Ghazipur',	09);
insert into districts (district_code, district_name, state_code) values (183,	'Gonda',	09);
insert into districts (district_code, district_name, state_code) values (188,	'Gorakhpur',	09);
insert into districts (district_code, district_name, state_code) values (168,	'Hamirpur',	09);
insert into districts (district_code, district_name, state_code) values (901,	'Hapur',	09);
insert into districts (district_code, district_name, state_code) values (155,	'Hardoi',	09);
insert into districts (district_code, district_name, state_code) values (144,	'Hathras',	09);
insert into districts (district_code, district_name, state_code) values (165,	'Jalaun',	09);
insert into districts (district_code, district_name, state_code) values (194,	'Jaunpur',	09);
insert into districts (district_code, district_name, state_code) values (166,	'Jhansi',	09);
insert into districts (district_code, district_name, state_code) values (160,	'Kannauj',	09);
insert into districts (district_code, district_name, state_code) values (163,	'Kanpur Dehat',	09);
insert into districts (district_code, district_name, state_code) values (164,	'Kanpur Nagar',	09);
insert into districts (district_code, district_name, state_code) values (202,	'Kasganj',	09);
insert into districts (district_code, district_name, state_code) values (174,	'Kaushambi',	09);
insert into districts (district_code, district_name, state_code) values (153,	'Kheri',	09);
insert into districts (district_code, district_name, state_code) values (189,	'Kushinagar',	09);
insert into districts (district_code, district_name, state_code) values (167,	'Lalitpur',	09);
insert into districts (district_code, district_name, state_code) values (157,	'Lucknow',	09);
insert into districts (district_code, district_name, state_code) values (169,	'Mahoba',	09);
insert into districts (district_code, district_name, state_code) values (187,	'Mahrajganj',	09);
insert into districts (district_code, district_name, state_code) values (148,	'Mainpuri',	09);
insert into districts (district_code, district_name, state_code) values (145,	'Mathura',	09);
insert into districts (district_code, district_name, state_code) values (192,	'Mau',	09);
insert into districts (district_code, district_name, state_code) values (138,	'Meerut',	09);
insert into districts (district_code, district_name, state_code) values (199,	'Mirzapur',	09);
insert into districts (district_code, district_name, state_code) values (135,	'Moradabad',	09);
insert into districts (district_code, district_name, state_code) values (133,	'Muzaffarnagar',	09);
insert into districts (district_code, district_name, state_code) values (151,	'Pilibhit',	09);
insert into districts (district_code, district_name, state_code) values (173,	'Pratapgarh',	09);
insert into districts (district_code, district_name, state_code) values (158,	'Rae Bareli',	09);
insert into districts (district_code, district_name, state_code) values (136,	'Rampur',	09);
insert into districts (district_code, district_name, state_code) values (132,	'Saharanpur',	09);
insert into districts (district_code, district_name, state_code) values (902,	'Sambhal',	09);
insert into districts (district_code, district_name, state_code) values (186,	'Sant Kabir Nagar',	09);
insert into districts (district_code, district_name, state_code) values (152,	'Shahjahanpur',	09);
insert into districts (district_code, district_name, state_code) values (903,	'Shamli',	09);
insert into districts (district_code, district_name, state_code) values (181,	'Shrawasti',	09);
insert into districts (district_code, district_name, state_code) values (184,	'Siddharthnagar',	09);
insert into districts (district_code, district_name, state_code) values (154,	'Sitapur',	09);
insert into districts (district_code, district_name, state_code) values (200,	'Sonbhadra',	09);
insert into districts (district_code, district_name, state_code) values (179,	'Sultanpur',	09);
insert into districts (district_code, district_name, state_code) values (156,	'Unnao',	09);
insert into districts (district_code, district_name, state_code) values (197,	'Varanasi',	09);
insert into districts (district_code, district_name, state_code) values (064,	'Almora',	05);
insert into districts (district_code, district_name, state_code) values (063,	'Bageshwar',	05);
insert into districts (district_code, district_name, state_code) values (057,	'Chamoli',	05);
insert into districts (district_code, district_name, state_code) values (065,	'Champawat',	05);
insert into districts (district_code, district_name, state_code) values (060,	'Dehradun',	05);
insert into districts (district_code, district_name, state_code) values (061,	'Garhwal',	05);
insert into districts (district_code, district_name, state_code) values (068,	'Hardwar',	05);
insert into districts (district_code, district_name, state_code) values (066,	'Nainital',	05);
insert into districts (district_code, district_name, state_code) values (062,	'Pithoragarh',	05);
insert into districts (district_code, district_name, state_code) values (058,	'Rudraprayag',	05);
insert into districts (district_code, district_name, state_code) values (059,	'Tehri Garhwal',	05);
insert into districts (district_code, district_name, state_code) values (067,	'Udham Singh Nagar',	05);
insert into districts (district_code, district_name, state_code) values (056,	'Uttarkashi',	05);
insert into districts (district_code, district_name, state_code) values (914,	'Alipurduar',	19);
insert into districts (district_code, district_name, state_code) values (339,	'Bankura',	19);
insert into districts (district_code, district_name, state_code) values (335,	'Barddhaman',	19);
insert into districts (district_code, district_name, state_code) values (334,	'Birbhum',	19);
insert into districts (district_code, district_name, state_code) values (331,	'Dakshin Dinajpur',	19);
insert into districts (district_code, district_name, state_code) values (327,	'Darjiling',	19);
insert into districts (district_code, district_name, state_code) values (341,	'Haora',	19);
insert into districts (district_code, district_name, state_code) values (338,	'Hugli',	19);
insert into districts (district_code, district_name, state_code) values (328,	'Jalpaiguri',	19);
insert into districts (district_code, district_name, state_code) values (950,	'Jhargram',	19);
insert into districts (district_code, district_name, state_code) values (949,	'Kalimpong',	19);
insert into districts (district_code, district_name, state_code) values (329,	'Koch Bihar',	19);
insert into districts (district_code, district_name, state_code) values (342,	'Kolkata',	19);
insert into districts (district_code, district_name, state_code) values (332,	'Maldah',	19);
insert into districts (district_code, district_name, state_code) values (333,	'Murshidabad',	19);
insert into districts (district_code, district_name, state_code) values (336,	'Nadia',	19);
insert into districts (district_code, district_name, state_code) values (337,	'North Twenty Four Parganas',	19);
insert into districts (district_code, district_name, state_code) values (951,	'Paschim Bardhaman',	19);
insert into districts (district_code, district_name, state_code) values (344,	'Paschim Medinipur',	19);
insert into districts (district_code, district_name, state_code) values (952,	'Purba Bardhaman',	19);
insert into districts (district_code, district_name, state_code) values (345,	'Purba Medinipur',	19);
insert into districts (district_code, district_name, state_code) values (340,	'Puruliya',	19);
insert into districts (district_code, district_name, state_code) values (343,	'South Twenty Four Parganas',	19);
insert into districts (district_code, district_name, state_code) values (330,	'Uttar Dinajpur',	19);
